name: angular

on:
  issue_comment:
    types: [created]

permissions: read-all

jobs:
  benchmark-compare:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/benchmark-compare ')}}
    steps:
      - uses: TheModdingInquisition/actions-team-membership@a69636a92bc927f32c3910baac06bacc949c984c # v1.0
        with:
          team: 'team'
          organization: angular
          token: ${{secrets.BENCHMARK_COMPARE_MEMBERSHIP_GITHUB_TOKEN}}
          exit: true

      - uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4
        with:
          comment-id: ${{github.event.comment.id}}
          token: '${{secrets.BENCHMARK_POST_RESULTS_GITHUB_TOKEN}}'
          reactions: 'rocket'

      - uses: alessbell/pull-request-comment-branch@aad01d65d6982b8eacabed5e9a684cd8ceb98da6 # v1.1
        id: comment-branch

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: ${{steps.comment-branch.outputs.head_owner}}/${{steps.comment-branch.outputs.head_repo}}
          ref: ${{steps.comment-branch.outputs.head_ref}}

      - uses: ./.github/actions/yarn-install

