name: Broken
on: [pull_request_review, pull_request_review_comment]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Injection
        run: echo ${{ github.event.pull_request }}
        
