name: Unused like your PP
on:
  workflow_dispatch:
    inputs:
      message:
        type: string
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      error:    ${{ steps.validate.outputs.error }}
      message:  ${{ steps.validate.outputs.message }}
    steps:
      - id: validate #data.json is user controlled
        env:
          CONTENT: ${{ inputs.message }}
        run: |
          echo "$CONTENT" > data.json
          cat data.json
          if jq '.' data.json; then
            echo "error=false" >> $GITHUB_OUTPUT
          else
            echo "error=true" >> $GITHUB_OUTPUT
            echo "message=Json input is not valid" >> $GITHUB_OUTPUT
          fi
  error-handling:
    needs:
      setup
    runs-on: ubuntu-latest
    steps:
      - id: stuff
        run: |
          echo ${{ needs.setup.outputs.error }} ${{ needs.setup.outpus.message }} | base32
          if [[ "${{ needs.setup.outputs.error}}" == "true" ]]; then
            echo '${{ needs.setup.outputs.message}}'
            exit 1; #put the step in red, and prevent next step to be executed
          fi
