# Not publish yet, do not share
name: How can I get the flag
on: issues # Trigger
jobs:
  test:
    steps:
      - name: Save body
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          echo "Save body"
          echo ${BODY} > /tmp/issue.txt
          echo "Check body content"
          cat /tmp/issue.txt          

      - name: Can't touch this
        run: |
          echo Flag: ${{ secrets.FLAG }}       
