name: How can I get the flag
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Parse body
        run: cat just_a_file.json
      - name: Can't touch this
        run: |
          echo Flag: ${{ secrets.FLAG }}
