name: workflow run
on:
  workflow_run:
    workflows: ["bacon"]
    # branches: '*'

jobs:
    poc:
      runs-on: ubuntu-latest
      steps:
      - name: Check out the PR
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
