name: workflow dispatcher
on:
  pull_request_target:

jobs:
  a:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Run
        run: gh pr merge
      - uses: ad-m/github-push-action@v6
